name: voiced
favicon: null
layout_spectrum: 0.8420458855107427
typography_spectrum: 0.8655259069055319
title: voiced
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.960171397542581
  lightness: 0.23224993399344385
  saturation: 0.966761939227581
  rhythmicContrast: 0.5075685104820877
purpose: []
