name: voiced
favicon: null
layout_spectrum: 0.8420458855107427
typography_spectrum: 0.05301
title: voiced
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe1d7'
    - '#a99f95'
    - '#090619'
    - '#757172'
    - '#282d31'
  brandStrength: 0.960171397542581
  lightness: 0.5
  saturation: 0.966761939227581
  rhythmicContrast: 0.75
purpose: []
